### ISSUE TITLE
AttributeError: 'Namespace' object has no attribute 'directory'

### ISSUE THREAD

**Issue by nemec** [citcheese/SqlParserPlus#1]
When running the following command I get an error:

    python SqlParserPlus.py -s 'some/folder/'

Stack trace:

```
Traceback (most recent call last):
  File "SqlParserPlus.py", line 1016, in <module>
    main()
  File "SqlParserPlus.py", line 1005, in main
    filepath = os.path.join(args.directory, x)
AttributeError: 'Namespace' object has no attribute 'directory'
```
```
$ python -V
Python 3.8.2
```

```
$ lsb_release -a
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04 LTS
Release:	20.04
Codename:	focal
```

Based on context, I assume you meant for line 1005 to read `filepath = os.path.join(item, x)` instead?

I see a similar issue on line 988:

    sqlconverter(args.filepath,format,get_encoding=ENCODING,dumpall = args.dumpall)
should be

    sqlconverter(item,format,get_encoding=ENCODING,dumpall = args.dumpall)

After making those changes, I was able to get results 😊

**Comment by citcheese** [comment]
whoops, yea had sql file and folder extract as separate functions before and decided to quickly just combine them and forgot to replace those lines. Thanks for the heads up! Fixed and pushed to main
